export const features = [
  'Dashboard',
  'Employee management',
  'Doctors',
  'Nurses',
  'Pharmacist',
  'Lab Technician',
  'Administrator',
  'FrontDesk',
  'Security',
  'OtherStaff',
  'Appointments',
  'Reports',
  'Disease-Management',
  'Tests',
  'Treatments',
  'Procedure Management',
  'Payouts',
  'Help',
  'Customer Management',
  'ConsentForms',
  'Vendor Management',
  'Pharmacy Management',
  'Push Notification',
  'Inventory Management',
  'Support',
  'Billing',
  'Analytics',
  'Tax reports',
  'Refer Doctor',
  // 'Patient Management'
]

export const actions = ['create', 'read', 'update', 'delete']
